on:
  push:
    branches:
      - main
      - dev
    tags:
      - '*'
  pull_request:

name: "CI checks"

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64 ]
        python-version: [ "3.10" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Code style & linting
        uses: wemake-services/wemake-python-styleguide@0.17.0
        with:
          reporter: 'github-pr-check'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
      - name: Install dependencies
        run: |
          # bedtools 2.30.0
          wget "https://github.com/arq5x/bedtools2/releases/download/v2.30.0/bedtools.static.binary"
          chmod a+x bedtools.static.binary
          sudo mv bedtools.static.binary /usr/bin/bedtools
          # Pip dependencies
          python -m pip install '.[develop]'
      - name: Mypy type checls
        run: |
          mypy src
      - name: Tests
        run: |
          pytest
